runtime: nodejs12
env: standard

automatic_scaling:
 min_instances: 1
 min_idle_instances: 1
 max_instances: 1

 # [START handlers]
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
# [END handlers]